name: poke_env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - scikit-image
  - scipy
  - imageio
  - pandas
  - protobuf
  - websockets
  #- pytorch
  #- cudatoolkit=11.3

  - pip:
    - stable-baselines3
    - sb3-contrib            
    - pyboy
    - networks
    - einops
    - tensorboard
    - gymnasium             
    - mediapy
    - pyyaml
