extends: base.yaml

num_cpu: 32

paths:
  session_root: "experiments/v1"

env:
  module: "frame_stack_env"
  class: "FrameStackEnv"

model:
  type: "PPO"
  policy: "MultiInputPolicy"

logging:
  save_freq: 2000

total_timesteps: 100000
save_freq: 163840
