extends: base.yaml

paths:
  session_root: "experiments/v3"

env:
  module: "lstm_env"
  class: "LSTMEnv"

model:
  type: "RecurrentPPO"
  policy: "MultiInputLstmPolicy"
  device: "cuda"
  batch_size: 1024
