extends: base.yaml

paths:
  session_root: "experiments/v4"

env:
  module: "lstm_env"
  class: "LSTMEnv"

model:
  type: "RecurrentPPOLD"
  policy: "MultiInputLstmPolicyLD"
  ld_coef: 0.1

logging:
  save_freq: 500
