extends: v4.yaml

paths:
  session_root: "experiments/v4_production"

env:
  max_steps: 327680

model:
  n_steps: 4096
  batch_size: 1024
  n_epochs: 3
  vf_coef: 0.5

logging:
  save_freq: 1000

save_freq: 16000
total_timesteps: 2e8
