extends: v4.yaml

paths:
  session_root: "experiments/v4_tick_test"

num_cpu: 32

env:
  max_steps: 1024
  stats_flush_freq: 50
  print_rewards: true
  debug_release_tick_render_off: true

model:
  # n_steps will be recalculated: 1024 // 16 = 64
  ld_coef: 0.1

total_timesteps: 1e6

logging:
  save_freq: 200
