extends: base.yaml

paths:
  session_root: "experiments/v3"

num_cpu: 16

env:
  module: "red_gym_env_lstm"
  class: "RedGymEnvLSTM"

model:
  type: "RecurrentPPO"
  policy: "MultiInputLstmPolicy"



